services:
  service:
    image: xiv-configuration-service
    container_name: xiv-configuration-service
    restart: unless-stopped
    build:
      context: .
      dockerfile: XivConfigurationService/XivConfigurationService/Dockerfile
    environment:
      LOGGING__LOGLEVEL__DEFAULT: Information
      LOGGING__LOGLEVEL__MICROSOFT.ASPNETCORE: Warning
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: true # necessary for OIDC in container, otherwise redirect URI uses HTTP
      OIDC_AUTHORITY: https://auth.dev.eorzea.online/realms/eorzea
      OIDC_CLIENT_ID: config
      OIDC_CLIENT_SECRET: